"""add verified and confidence_score to issue_contents

Revision ID: 0e41028ae527
Revises: 87ccf6383ee4
Create Date: 2025-12-24 23:11:24.330723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e41028ae527'
down_revision: Union[str, None] = '87ccf6383ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_contents', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('issue_contents', sa.Column('confidence_score', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_contents', 'confidence_score')
    op.drop_column('issue_contents', 'verified')
    # ### end Alembic commands ###
