"""rename sessions_created to issues_created

Revision ID: 17eabc19eeda
Revises: 9d0ef2698d30
Create Date: 2025-12-23 12:02:28.994211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17eabc19eeda'
down_revision: Union[str, None] = '9d0ef2698d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_runs', sa.Column('issues_created', sa.Integer(), nullable=False))
    op.drop_column('batch_runs', 'sessions_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_runs', sa.Column('sessions_created', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('batch_runs', 'issues_created')
    # ### end Alembic commands ###
