"""add videos and insights

Revision ID: 23a8fac0cb43
Revises: 57e7d43726c4
Create Date: 2025-12-19 22:00:29.478702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a8fac0cb43'
down_revision: Union[str, None] = '57e7d43726c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_insights',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('verified_angles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_directions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['issue_daily_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_videos',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('angle', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['issue_daily_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_comments',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['issue_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comments')
    op.drop_table('issue_videos')
    op.drop_table('issue_insights')
    # ### end Alembic commands ###
