"""add issue_contents and issue_embeddings

Revision ID: 87ccf6383ee4
Revises: 5870e84c60f8
Create Date: 2025-12-24 11:59:06.336356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ccf6383ee4'
down_revision: Union[str, None] = '5870e84c60f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
