"""add_has_workspace_to_users

Revision ID: 9d0ef2698d30
Revises: df4db7884e2c
Create Date: 2025-12-23 10:45:28.665278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0ef2698d30'
down_revision: Union[str, None] = 'df4db7884e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_workspace', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_workspace')
    # ### end Alembic commands ###
