"""add_title_embedding_to_issue_articles

Revision ID: a29a805ba327
Revises: 62f11dc80ba1
Create Date: 2025-12-29 14:44:11.385379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a29a805ba327'
down_revision: Union[str, None] = '62f11dc80ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_articles', sa.Column('title_embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_articles', 'title_embedding')
    # ### end Alembic commands ###
