"""refactor workspace user relation

Revision ID: df4db7884e2c
Revises: 23a8fac0cb43
Create Date: 2025-12-21 02:06:33.696941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4db7884e2c'
down_revision: Union[str, None] = '23a8fac0cb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('workspaces', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('workspaces', sa.Column('category_filter', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('notification_enabled', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'workspaces', ['user_id'])
    op.create_foreign_key(None, 'workspaces', 'users', ['user_id'], ['id'])
    op.drop_column('workspaces', 'name')
    op.drop_column('workspaces', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_column('workspaces', 'notification_enabled')
    op.drop_column('workspaces', 'category_filter')
    op.drop_column('workspaces', 'timezone')
    op.drop_column('workspaces', 'user_id')
    # ### end Alembic commands ###
