"""add issue_keywords table

Revision ID: eaadcadd1865
Revises: 17eabc19eeda
Create Date: 2025-12-23 13:26:25.132192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaadcadd1865'
down_revision: Union[str, None] = '17eabc19eeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_keywords',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['issue_daily_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_keywords')
    # ### end Alembic commands ###
